# Generated by Django 6.0.5 on 2026-09-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_review_author_name_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('logo', models.ImageField(blank=True, upload_to='partners/', verbose_name='Логотип')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'компания-партнер',
                'verbose_name_plural': 'компании-партнеры',
                'ordering': ['name'],
            },
        ),
    ]
