# Generated by Django 6.0.5 on 2026-09-21 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partnercompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(default='Сертификат качества № CS-2026: услуги автосалона соответствуют внутреннему стандарту обслуживания.', verbose_name='Сертификат'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(default='ООО CarShowroom, УНП 193000001, г. Минск, проспект Независимости, 4', verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, upload_to='company/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])], verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='CompanyHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('description', models.CharField(max_length=300, verbose_name='Событие')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='core.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'событие истории компании',
                'verbose_name_plural': 'история компании по годам',
                'ordering': ['year'],
                'constraints': [models.UniqueConstraint(fields=('company', 'year'), name='unique_company_history_year')],
            },
        ),
    ]
