# Generated by Django 6.0.5 on 2026-05-16 10:19

import django.core.validators
import django.db.models.deletion
import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=80, verbose_name='Отчество')),
                ('birth_date', models.DateField(validators=[sales.models.validate_adult], verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +375 (29) XXX-XX-XX.', regex='^\\+375 \\((29|33|44|25)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=80, verbose_name='Отчество')),
                ('position', models.CharField(max_length=120, verbose_name='Должность')),
                ('birth_date', models.DateField(validators=[sales.models.validate_adult], verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +375 (29) XXX-XX-XX.', regex='^\\+375 \\((29|33|44|25)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('clients', models.ManyToManyField(blank=True, related_name='employees', to='sales.client', verbose_name='Клиенты сотрудника')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('paid', 'Оплачен'), ('delivered', 'Выдан клиенту'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки/выдачи')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='showroom.car', verbose_name='Автомобиль')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(verbose_name='Дата оплаты')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='sales.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'ordering': ['-paid_at'],
            },
        ),
    ]
