# Generated by Django 6.0.5 on 2026-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_client_user_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выдачи'),
        ),
    ]
